print("             へ   ♡    ╱|、   ")
print("         ૮ -  ՛)      (` - 7")
print("         / ⁻  ៸|      |、 ⁻〵")
print("     乀 (ˍ,  ل ل      じしˍ,)ノ")
print("dream")
print("        ╭ ◜◝ ͡ ◝ ͡ ◜◝ ╮ ")
print("      ♡  ∧＿∧ ＿∧  ♡")
print("  ♡     (⸝⸝_  ̫_) _⸝⸝)   ♡")
print("      ♡ /⌒ づ⊂⌒ヽ ♡")
print("   O     ╰ ◟   ͜   ◞ ╯")
print(" o")
print(" °∩――――――――∩")
print(" || ∧ ﾍ　  ||")
print(" ||(*´ ｰ`) ZZzz")
print(" |ﾉ^⌒⌒づ`￣   ＼")
print("(　ノ　　⌒ ヽ  ＼")
print(" ＼   ||￣￣￣￣||")
print("　＼,ﾉ||        ||")